/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "VRT-Control-Protocol"
 * 	found in "../../protocol/vrt-ctrl-asn1-types.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#include <vrtc/asn1c/asn_internal.h>

#include <vrtc/asn1c/Complex-int.h>

static asn_TYPE_member_t asn_MBR_Complex_int_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Complex_int, real),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"real"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Complex_int, imag),
		(ASN_TAG_CLASS_UNIVERSAL | (2 << 2)),
		0,
		&asn_DEF_NativeInteger,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imag"
		},
};
static ber_tlv_tag_t asn_DEF_Complex_int_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Complex_int_tag2el_1[] = {
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 0, 0, 1 }, /* real at 34 */
    { (ASN_TAG_CLASS_UNIVERSAL | (2 << 2)), 1, -1, 0 } /* imag at 36 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Complex_int_specs_1 = {
	sizeof(struct Complex_int),
	offsetof(struct Complex_int, _asn_ctx),
	asn_MAP_Complex_int_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Complex_int = {
	"Complex-int",
	"Complex-int",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Complex_int_tags_1,
	sizeof(asn_DEF_Complex_int_tags_1)
		/sizeof(asn_DEF_Complex_int_tags_1[0]), /* 2 */
	asn_DEF_Complex_int_tags_1,	/* Same as above */
	sizeof(asn_DEF_Complex_int_tags_1)
		/sizeof(asn_DEF_Complex_int_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_Complex_int_1,
	2,	/* Elements count */
	&asn_SPC_Complex_int_specs_1	/* Additional specs */
};

