/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "VRT-Control-Protocol"
 * 	found in "../../protocol/vrt-ctrl-asn1-types.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#include <vrtc/asn1c/asn_internal.h>

#include <vrtc/asn1c/Complex-float.h>

static asn_TYPE_member_t asn_MBR_Complex_float_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct Complex_float, real),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_IEEE_float,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"real"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct Complex_float, imag),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_IEEE_float,
		0,	/* Defer constraints checking to the member type */
		0,	/* PER is not compiled, use -gen-PER */
		0,
		"imag"
		},
};
static ber_tlv_tag_t asn_DEF_Complex_float_tags_1[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_TYPE_tag2member_t asn_MAP_Complex_float_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 0, 0, 1 }, /* real at 41 */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 1, -1, 0 } /* imag at 43 */
};
static asn_SEQUENCE_specifics_t asn_SPC_Complex_float_specs_1 = {
	sizeof(struct Complex_float),
	offsetof(struct Complex_float, _asn_ctx),
	asn_MAP_Complex_float_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* Start extensions */
	-1	/* Stop extensions */
};
asn_TYPE_descriptor_t asn_DEF_Complex_float = {
	"Complex-float",
	"Complex-float",
	SEQUENCE_free,
	SEQUENCE_print,
	SEQUENCE_constraint,
	SEQUENCE_decode_ber,
	SEQUENCE_encode_der,
	SEQUENCE_decode_xer,
	SEQUENCE_encode_xer,
	0, 0,	/* No PER support, use "-gen-PER" to enable */
	0,	/* Use generic outmost tag fetcher */
	asn_DEF_Complex_float_tags_1,
	sizeof(asn_DEF_Complex_float_tags_1)
		/sizeof(asn_DEF_Complex_float_tags_1[0]), /* 2 */
	asn_DEF_Complex_float_tags_1,	/* Same as above */
	sizeof(asn_DEF_Complex_float_tags_1)
		/sizeof(asn_DEF_Complex_float_tags_1[0]), /* 2 */
	0,	/* No PER visible constraints */
	asn_MBR_Complex_float_1,
	2,	/* Elements count */
	&asn_SPC_Complex_float_specs_1	/* Additional specs */
};

