--  -*- asn1-mode -*-
--
--  Copyright 2010 Free Software Foundation, Inc.
-- 
--  This program is free software: you can redistribute it and/or modify
--  it under the terms of the GNU General Public License as published by
--  the Free Software Foundation, either version 3 of the License, or
--  (at your option) any later version.
-- 
--  This program is distributed in the hope that it will be useful,
--  but WITHOUT ANY WARRANTY; without even the implied warranty of
--  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
--  GNU General Public License for more details.
-- 
--  You should have received a copy of the GNU General Public License
--  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-- 

VRT-Control-Protocol { iso org(3) dod(6) internet(1) private(4) enterprise(1)
		       gnu(11591) radio(7) protocol(0) vrt-ctrl(0) rev(0) }
DEFINITIONS
AUTOMATIC TAGS ::=
BEGIN
END

