/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "VRT-Control-Protocol"
 * 	found in "../../protocol/vrt-ctrl-asn1-types.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Complex_int_H_
#define	_Complex_int_H_


#include <vrtc/asn1c/asn_application.h>

/* Including external dependencies */
#include <vrtc/asn1c/NativeInteger.h>
#include <vrtc/asn1c/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Complex-int */
typedef struct Complex_int {
	long	 real;
	long	 imag;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Complex_int_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Complex_int;

#ifdef __cplusplus
}
#endif

#endif	/* _Complex_int_H_ */
