/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "VRT-Control-Protocol"
 * 	found in "../../protocol/vrt-ctrl-asn1-types.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_Complex_float_H_
#define	_Complex_float_H_


#include <vrtc/asn1c/asn_application.h>

/* Including external dependencies */
#include <vrtc/asn1c/IEEE-float.h>
#include <vrtc/asn1c/constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Complex-float */
typedef struct Complex_float {
	IEEE_float_t	 real;
	IEEE_float_t	 imag;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Complex_float_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Complex_float;

#ifdef __cplusplus
}
#endif

#endif	/* _Complex_float_H_ */
