/*
 * Generated by asn1c-0.9.21 (http://lionet.info/asn1c)
 * From ASN.1 module "VRT-Control-Protocol"
 * 	found in "../../protocol/vrt-ctrl-asn1-types.asn1"
 * 	`asn1c -fskeletons-copy`
 */

#ifndef	_IEEE_float_H_
#define	_IEEE_float_H_


#include <vrtc/asn1c/asn_application.h>

/* Including external dependencies */
#include <vrtc/asn1c/NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* IEEE-float */
typedef long	 IEEE_float_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IEEE_float;
asn_struct_free_f IEEE_float_free;
asn_struct_print_f IEEE_float_print;
asn_constr_check_f IEEE_float_constraint;
ber_type_decoder_f IEEE_float_decode_ber;
der_type_encoder_f IEEE_float_encode_der;
xer_type_decoder_f IEEE_float_decode_xer;
xer_type_encoder_f IEEE_float_encode_xer;

#ifdef __cplusplus
}
#endif

#endif	/* _IEEE_float_H_ */
